version: '3.4'

services:
  database:
    image: postgres:11
    container_name: database_pg
    #restart: always
    environment:
      - POSTGRES_PASSWORD=docker
    ports:
      - "5432:5432"
  mongo:
    image: mongo
    container_name: mongo_db
    #restart: always
    ports:
      - "27017:27017"
